pipeline {
    agent any

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ShishirtejA/Django-multi-Environment.git'
            }
        }

        stage('Deploy DEV') {
            steps {
                sh '''
                docker compose -f docker-compose.dev.yml down || true
                docker compose -f docker-compose.dev.yml up -d --build
                '''
            }
        }

        stage('Deploy QA') {
            steps {
                sh '''
                docker compose -f docker-compose.qa.yml down || true
                docker compose -f docker-compose.qa.yml up -d --build
                '''
            }
        }

        stage('Approve PROD') {
            steps {
                input message: 'Deploy to PROD?', ok: 'Deploy'
            }
        }

        stage('Deploy PROD') {
            steps {
                sh '''
                docker compose -f docker-compose.prod.yml down || true
                docker compose -f docker-compose.prod.yml up -d --build
                '''
            }
        }
    }
}

